# Generated by Django 4.2.2 on 2023-10-14 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_category_status_alter_product_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(max_length=256)),
                ('status', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], max_length=100, verbose_name='Status of the category')),
            ],
            options={
                'verbose_name_plural': 'Warehouses',
                'db_table': 'Warehouse',
            },
        ),
    ]
