# Generated by Django 4.2.2 on 2023-10-15 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_warehouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleSupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidadMinima', models.FloatField()),
                ('cantidadMaxima', models.FloatField()),
                ('idProveedor', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Warehouses',
                'db_table': 'RuleSupply',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='warehouse',
            field=models.ForeignKey(db_column='warehouse', default=None, on_delete=django.db.models.deletion.CASCADE, related_name='warehouse', to='products.warehouse'),
        ),
        migrations.AddField(
            model_name='product',
            name='ruleSupply',
            field=models.ForeignKey(db_column='ruleSupply', default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ruleSupply', to='products.rulesupply'),
        ),
    ]
