# Generated by Django 4.2.2 on 2023-10-15 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_rulesupply_product_warehouse_product_rulesupply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ruleSupply',
            field=models.ForeignKey(blank=True, db_column='ruleSupply', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ruleSupply', to='products.rulesupply'),
        ),
    ]
