# Generated by Django 4.2.2 on 2023-10-15 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_product_rulesupply'),
    ]

    operations = [
        migrations.AddField(
            model_name='rulesupply',
            name='status',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='INACTIVO', max_length=100, verbose_name='Status of the rule supply'),
        ),
    ]
