# Generated by Django 4.2.2 on 2023-10-15 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_rename_last_name_supplier_company_name_and_more'),
        ('products', '0012_rulesupply_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rulesupply',
            old_name='cantidadMaxima',
            new_name='maximumQuantity',
        ),
        migrations.RenameField(
            model_name='rulesupply',
            old_name='cantidadMinima',
            new_name='minimumAmount',
        ),
        migrations.RemoveField(
            model_name='rulesupply',
            name='idProveedor',
        ),
        migrations.AddField(
            model_name='rulesupply',
            name='supplier',
            field=models.ForeignKey(blank=True, db_column='supplier', default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='suppliers.supplier'),
        ),
    ]
