# Generated by Django 4.2.2 on 2023-10-16 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suppliers', '0002_rename_last_name_supplier_company_name_and_more'),
        ('products', '0015_product_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grand_total', models.FloatField(default=0)),
                ('opening_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], max_length=100, verbose_name='Status of the category')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='suppliers.supplier')),
            ],
            options={
                'db_table': 'ShoppingList',
            },
        ),
        migrations.CreateModel(
            name='BuyDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('total_detail', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.product')),
                ('shoppinglist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy_details', to='buys.shoppinglist')),
            ],
            options={
                'db_table': 'BuyDetails',
            },
        ),
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_date', models.DateTimeField(blank=True, null=True)),
                ('grand_total', models.FloatField(default=0)),
                ('shoppinglist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buys.shoppinglist')),
            ],
        ),
    ]
