# Generated by Django 4.2.2 on 2023-10-17 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buys', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='buy',
            table='Buy',
        ),
    ]
