# Generated by Django 4.2.2 on 2023-10-04 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('products', '0006_product_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('sub_total', models.FloatField(default=0)),
                ('grand_total', models.FloatField(default=0)),
                ('tax_amount', models.FloatField(default=0)),
                ('tax_percentage', models.FloatField(default=0)),
                ('amount_payed', models.FloatField(default=0)),
                ('amount_change', models.FloatField(default=0)),
                ('customer', models.ForeignKey(db_column='customer', on_delete=django.db.models.deletion.DO_NOTHING, to='customers.customer')),
            ],
            options={
                'db_table': 'Sales',
            },
        ),
        migrations.CreateModel(
            name='SaleDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('total_detail', models.FloatField()),
                ('product', models.ForeignKey(db_column='product', on_delete=django.db.models.deletion.DO_NOTHING, to='products.product')),
                ('sale', models.ForeignKey(db_column='sale', on_delete=django.db.models.deletion.DO_NOTHING, to='sales.sale')),
            ],
            options={
                'db_table': 'SaleDetails',
            },
        ),
        migrations.CreateModel(
            name='CashRegisterOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_date', models.DateTimeField(blank=True, null=True)),
                ('initial_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('final_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'CashRegisterOpenings',
            },
        ),
    ]
