# Generated by Django 4.1.5 on 2023-10-05 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_sale_cashregisteropening'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashregisteropening',
            name='total_sesion',
            field=models.FloatField(default=0),
        ),
    ]
